//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductosCoppel.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class coppelEntities : DbContext
    {
        public coppelEntities()
            : base("name=coppelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<R_Clases_Result> R_Clases()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<R_Clases_Result>("R_Clases");
        }
    
        public virtual ObjectResult<R_Departamentos_Result> R_Departamentos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<R_Departamentos_Result>("R_Departamentos");
        }
    
        public virtual ObjectResult<R_Familias_Result> R_Familias()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<R_Familias_Result>("R_Familias");
        }
    
        public virtual int C_Producto(string sku, string articulo, string marca, string modelo, Nullable<int> departamento, Nullable<int> clase, Nullable<int> familia, Nullable<System.DateTime> f_alta, Nullable<int> stock, Nullable<int> cantidad, Nullable<bool> descontinuado, Nullable<System.DateTime> f_baja)
        {
            var skuParameter = sku != null ?
                new ObjectParameter("Sku", sku) :
                new ObjectParameter("Sku", typeof(string));
    
            var articuloParameter = articulo != null ?
                new ObjectParameter("Articulo", articulo) :
                new ObjectParameter("Articulo", typeof(string));
    
            var marcaParameter = marca != null ?
                new ObjectParameter("Marca", marca) :
                new ObjectParameter("Marca", typeof(string));
    
            var modeloParameter = modelo != null ?
                new ObjectParameter("Modelo", modelo) :
                new ObjectParameter("Modelo", typeof(string));
    
            var departamentoParameter = departamento.HasValue ?
                new ObjectParameter("Departamento", departamento) :
                new ObjectParameter("Departamento", typeof(int));
    
            var claseParameter = clase.HasValue ?
                new ObjectParameter("Clase", clase) :
                new ObjectParameter("Clase", typeof(int));
    
            var familiaParameter = familia.HasValue ?
                new ObjectParameter("Familia", familia) :
                new ObjectParameter("Familia", typeof(int));
    
            var f_altaParameter = f_alta.HasValue ?
                new ObjectParameter("F_alta", f_alta) :
                new ObjectParameter("F_alta", typeof(System.DateTime));
    
            var stockParameter = stock.HasValue ?
                new ObjectParameter("Stock", stock) :
                new ObjectParameter("Stock", typeof(int));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("Cantidad", cantidad) :
                new ObjectParameter("Cantidad", typeof(int));
    
            var descontinuadoParameter = descontinuado.HasValue ?
                new ObjectParameter("Descontinuado", descontinuado) :
                new ObjectParameter("Descontinuado", typeof(bool));
    
            var f_bajaParameter = f_baja.HasValue ?
                new ObjectParameter("F_baja", f_baja) :
                new ObjectParameter("F_baja", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("C_Producto", skuParameter, articuloParameter, marcaParameter, modeloParameter, departamentoParameter, claseParameter, familiaParameter, f_altaParameter, stockParameter, cantidadParameter, descontinuadoParameter, f_bajaParameter);
        }
    }
}
